<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Design SOP _e____3b139a12-bbae-4df0-9_8683d5</name>
   <tag></tag>
   <elementGuidId>b2aa6f03-300c-44ab-b29b-6a0ae87863a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e____3b139a12-bbae-4df0-95d0-f1ad957539df____1637352586624340219</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e____3b139a12-bbae-4df0-95d0-f1ad957539df____1637352586624340219']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e____3b139a12-bbae-4df0-95d0-f1ad957539df____1637352586624340219</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e____3b139a12-bbae-4df0-95d0-f1ad957539df____1637352586624340219</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Design SOP: ** value of: </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control amxdata-form-control waf-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript: updateCurrentFocusedControl('e____3b139a12-bbae-4df0-95d0-f1ad957539df')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e____3b139a12-bbae-4df0-95d0-f1ad957539df____1637352586624340219&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AIMS/Components/Edit/Edit Asset/Channel/Page_AMX Web Application - Home/Page_AMX Web Application - Home/iframe_Asset Description_detailsObj</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e____3b139a12-bbae-4df0-95d0-f1ad957539df____1637352586624340219']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='col_e____3b139a12-bbae-4df0-95d0-f1ad957539df____1637352586624340219']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[4]/input</value>
   </webElementXpaths>
</WebElementEntity>
