<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ST2000031Asset DefectStructural damage _0318a3</name>
   <tag></tag>
   <elementGuidId>7f7df2e3-4771-4f12-aeb2-345dc9aa02c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grid_7dc6b56a-8d89-4388-a2de-6c1687e89880_0d8fa155-dbaf-4461-b4ad-2e59a745c7c1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid_7dc6b56a-8d89-4388-a2de-6c1687e89880_0d8fa155-dbaf-4461-b4ad-2e59a745c7c1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid_7dc6b56a-8d89-4388-a2de-6c1687e89880_0d8fa155-dbaf-4461-b4ad-2e59a745c7c1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>amxDataTableDiv border</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ST2000031Asset DefectStructural damage to assetTest AutomationUrgent15-09-202013-10-2020</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid_7dc6b56a-8d89-4388-a2de-6c1687e89880_0d8fa155-dbaf-4461-b4ad-2e59a745c7c1&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AIMS/Components/Create/Create Defect/Page_AMX Web Application - Home/iframe_AMX ID_detailsObj</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='grid_7dc6b56a-8d89-4388-a2de-6c1687e89880_0d8fa155-dbaf-4461-b4ad-2e59a745c7c1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='collabel_____7dc6b56a-8d89-4388-a2de-6c1687e89880____1637357636422752141']/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Date'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Raised'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
