<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Defect Comments _e____5b43d6c5-20f_7ab4a5</name>
   <tag></tag>
   <elementGuidId>75cbba37-90d5-40d6-b7b8-d816e9ef0c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e____5b43d6c5-20fe-42ec-8778-74dc5a7198cc____1637357635626070850</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='e____5b43d6c5-20fe-42ec-8778-74dc5a7198cc____1637357635626070850']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e____5b43d6c5-20fe-42ec-8778-74dc5a7198cc____1637357635626070850</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e____5b43d6c5-20fe-42ec-8778-74dc5a7198cc____1637357635626070850</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Defect Comments: ** value of: </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control amxdata-form-control  waf-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript: updateCurrentFocusedControl('e____5b43d6c5-20fe-42ec-8778-74dc5a7198cc')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e____5b43d6c5-20fe-42ec-8778-74dc5a7198cc____1637357635626070850&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AIMS/Components/Create/Create Defect/Page_AMX Web Application - Home/iframe_AMX ID_detailsObj</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='e____5b43d6c5-20fe-42ec-8778-74dc5a7198cc____1637357635626070850']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='col_e____5b43d6c5-20fe-42ec-8778-74dc5a7198cc____1637357635626070850']/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/textarea</value>
   </webElementXpaths>
</WebElementEntity>
