<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Automation (782231)</name>
   <tag></tag>
   <elementGuidId>1237bbd4-4ff9-4ac0-a995-a9a60dd8d56f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.propagateEvent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;form1&quot;)/div[4]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/ul[1]/li[1]/a[@class=&quot;propagateEvent&quot;][count(. | //*[(text() = 'Automation (782231)' or . = 'Automation (782231)') and @ref_element = 'Object Repository/AIMS/Components/Create/Relationship/Page_AMX Web Application - Home/iframe_AMX ID_detailsObj']) = count(//*[(text() = 'Automation (782231)' or . = 'Automation (782231)') and @ref_element = 'Object Repository/AIMS/Components/Create/Relationship/Page_AMX Web Application - Home/iframe_AMX ID_detailsObj'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/div[4]/div[2]/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>propagateEvent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-macroselect</name>
      <type>Main</type>
      <value>Automation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>selectasset.aspx?assetid=dde6acbf-563a-4fce-b593-da713afbd0d1&amp;id=9793454c-b38b-483c-a9f3-9487dac37e96&amp;toplevelid=9793454c-b38b-483c-a9f3-9487dac37e96&amp;action=selectchildasset&amp;mode=view&amp;tabseparator=1599669585285&amp;key=assets</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation (782231)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[4]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/ul[1]/li[1]/a[@class=&quot;propagateEvent&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AIMS/Components/Create/Relationship/Page_AMX Web Application - Home/iframe_AMX ID_detailsObj</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[4]/div[2]/div/ul/li/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Automation (782231)')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automation (782231)']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'selectasset.aspx?assetid=dde6acbf-563a-4fce-b593-da713afbd0d1&amp;id=9793454c-b38b-483c-a9f3-9487dac37e96&amp;toplevelid=9793454c-b38b-483c-a9f3-9487dac37e96&amp;action=selectchildasset&amp;mode=view&amp;tabseparator=1599669585285&amp;key=assets')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
   </webElementXpaths>
</WebElementEntity>
