<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChooseFile</name>
   <tag></tag>
   <elementGuidId>e9819b33-fc14-45a3-a38c-e7676dfcb09e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[3]/div[2]/div[7]/div/div[3]/table/tbody/tr[1]/td/div[2]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>/html/body/form/div[3]/div[2]/div[7]/div/div[3]/table/tbody/tr[1]/td/div[2]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@input = 'file element' and @ref_element = 'Object Repository/AIMS/Components/Create/Add Document/Page_AMX Web Application - Home/Page_AMX Web Application - Home/iframe_Defect Status_detailsObj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e____22b8f891-c3b3-4a7e-8003-869524dfadf1$ctl02</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e____22b8f891-c3b3-4a7e-8003-869524dfadf1_ctl02</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>input</name>
      <type>Main</type>
      <value>file element</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AIMS/Components/Create/Add Document/Page_AMX Web Application - Home/Page_AMX Web Application - Home/iframe_Defect Status_detailsObj</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
</WebElementEntity>
