<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Effective Crest Level Date _e____76dd_bb620d</name>
   <tag></tag>
   <elementGuidId>eac6c962-6532-47b2-9a73-a71469f1b51e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e____76ddf8e5-b9ee-4201-bea7-50af7113184f____1637351739477979842</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e____76ddf8e5-b9ee-4201-bea7-50af7113184f____1637351739477979842']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e____76ddf8e5-b9ee-4201-bea7-50af7113184f____1637351739477979842</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e____76ddf8e5-b9ee-4201-bea7-50af7113184f____1637351739477979842</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control amxdata-form-control hasDatePicker hasDatepicker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript: updateCurrentFocusedControl('e____76ddf8e5-b9ee-4201-bea7-50af7113184f')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e____76ddf8e5-b9ee-4201-bea7-50af7113184f____1637351739477979842&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AIMS/Components/Edit/Edit Asset/Page_AMX Web Application - Home/iframe_Asset Description_detailsObj</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e____76ddf8e5-b9ee-4201-bea7-50af7113184f____1637351739477979842']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='col_e____76ddf8e5-b9ee-4201-bea7-50af7113184f____1637351739477979842']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[4]/input</value>
   </webElementXpaths>
</WebElementEntity>
