<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alternative Purpose 1</name>
   <tag></tag>
   <elementGuidId>1d0e7dc7-79e8-459c-94e9-d8f41d65f0d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @readonly = 'readonly' and @title = 'Alternative Purpose 1: value of: ' and @class = 'form-control amxdata-form-control amx-lookup-box' and @ref_element = 'Object Repository/AIMS/Components/Create/Asset Aid to Navigation/Page_AIMS-AMX - Home/Page_AIMS-AMX - Home/iframe_Asset Type_detailsObj']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e____3976fd0a_51dc_4ecf_8ed9_7002b410a1e8____1637350870378371137_display']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e____3976fd0a_51dc_4ecf_8ed9_7002b410a1e8____1637350870378371137_display</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e____3976fd0a_51dc_4ecf_8ed9_7002b410a1e8____1637350870378371137_display</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e____3976fd0a_51dc_4ecf_8ed9_7002b410a1e8____1637350870378371137_display</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Alternative Purpose 1: value of: </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control amxdata-form-control amx-lookup-box</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>e____3976fd0a_51dc_4ecf_8ed9_7002b410a1e8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e____3976fd0a_51dc_4ecf_8ed9_7002b410a1e8____1637350870378371137_display&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AIMS/Components/Create/Asset Aid to Navigation/Page_AIMS-AMX - Home/Page_AIMS-AMX - Home/iframe_Asset Type_detailsObj</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e____3976fd0a_51dc_4ecf_8ed9_7002b410a1e8____1637350870378371137_display']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_e____3976fd0a_51dc_4ecf_8ed9_7002b410a1e8']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
