<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Asset Owner _dropDownButton_e____a42_a9a11a</name>
   <tag></tag>
   <elementGuidId>4ef2f8e5-d1dc-4596-aee1-1720495911d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @data-macro = 'dropDownButton_OwnerID' and @ref_element = 'Object Repository/AIMS/Components/Create/Asset Aid to Navigation/Page_AIMS-AMX - Home/iframe_Asset Type_detailsObj']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropDownButton_e____a42c655f_1cf9_4603_b590_55a85378bd94']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropDownButton_e____a42c655f_1cf9_4603_b590_55a85378bd94</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>e____a42c655f_1cf9_4603_b590_55a85378bd94</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default amx-lookup-ddl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pop</name>
      <type>Main</type>
      <value>{&quot;Lookupcode&quot;:&quot;TABLE_ORGANISATIONS&quot;,&quot;Title&quot;:&quot;Asset Owner: **&quot;,&quot;FieldName&quot;:&quot;OwnerID&quot;,&quot;EntityKey&quot;:&quot;assets&quot;,&quot;DataID&quot;:&quot;3f4cb021-eb40-49d1-adaf-aa2baf37ce72&quot;,&quot;ParentID&quot;:&quot;&quot;,&quot;ParentParentID&quot;:&quot;&quot;,&quot;AdvancedFilter&quot;:&quot;&quot;,&quot;ControlID&quot;:null,&quot;Sql&quot;:&quot;&quot;,&quot;tabKey&quot;:&quot;1599483662965&quot;,&quot;SearchTerm&quot;:null,&quot;HasRecommend&quot;:false,&quot;RecommendationReason&quot;:null,&quot;ShowAll&quot;:false,&quot;IsSupportLookup&quot;:false,&quot;FromGrid&quot;:false,&quot;hasParentOnGrid&quot;:false,&quot;hasParentParentOnGrid&quot;:false,&quot;ServerSearch&quot;:false,&quot;displayfield&quot;:0,&quot;displayfieldother&quot;:null}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropDownButton_e____a42c655f_1cf9_4603_b590_55a85378bd94</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-macro</name>
      <type>Main</type>
      <value>dropDownButton_OwnerID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropDownButton_e____a42c655f_1cf9_4603_b590_55a85378bd94&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AIMS/Components/Create/Asset Aid to Navigation/Page_AIMS-AMX - Home/iframe_Asset Type_detailsObj</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropDownButton_e____a42c655f_1cf9_4603_b590_55a85378bd94']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buttondiv_e____a42c655f_1cf9_4603_b590_55a85378bd94']/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Owner: **'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Target Condition: **'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Operator: **'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Maintainer: **'])[1]/preceding::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td/div/div/button</value>
   </webElementXpaths>
</WebElementEntity>
